#! /bin/sh

set -e

[[ "$DEBUG" == "true" ]] && set -x

addgroup -g ${PGID:-1000} rutorrent && adduser -h / -s /bin/sh -G rutorrent -D -u ${PUID:-1000} rutorrent

chown -R rutorrent:rutorrent \
  /run /var/lib/nginx /var/log/nginx /var/www/rutorrent

su rutorrent -c " /usr/bin/supervisord -c /etc/supervisor.d/conf.d/supervisord.conf"
