#!/bin/sh
PUID=${PUID:=1000}
PGID=${PGID:=1000}

#chown -R "$PUID:$PGID" /var/www
#chown -R "$PUID:$PGID" /var/lib/nginx
#chown -R "$PUID:$PGID" /var/tmp/nginx

/usr/bin/supervisord -c /etc/supervisord.conf
